language: python
python: 3.4
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py27-lint
before_install: sudo apt-get build-dep python-pgmagick
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
